config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # For opening the email in the web browser in non production environments
  if ENV["EMAIL_DELIVERY_METHOD"] == "letter_opener_web"
    mount LetterOpenerWeb::Engine, at: "/sent_emails"
  end

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(username),
      ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
      ActiveSupport::SecurityUtils.secure_compare(
        ::Digest::SHA256.hexdigest(password),
        ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
  end
  mount Sidekiq::Web, at: "/sidekiq"

  root to: "root#index"
  draw(:internal_api)
  draw(:api)
  draw(:device_api)
  resources :dashboard, only: [:index]

  # get "*path", to: "home#index", via: :all
  resource :company, only: [:new, :show, :create, :update], controller: :companies do
    resource :purge_logo, only: [:destroy], controller: "companies/purge_logo"
  end

  resources :workspaces, only: [:update]

  resources :invoices, only: [], module: :invoices do
    resources :payments, only: [:new] do
      collection do
        get :success
        get :cancel
      end
    end

    member do
      get :view, to: "view#show", as: :view
    end
  end

  namespace :invitations do
    resources :accepts, only: [:index], controller: "accept"
  end

  get "users/invitation/accept", to: "invitations/accept#show"
  get "payments/settings/stripe/connect/refresh", to: "payment_settings#refresh_stripe_connect"
  get "payments/settings/*path", to: "payment_settings#index", via: :all
  get "payments/settings", to: "payment_settings#index"

  resource :email_confirmation, only: :show do
    get :resend
  end

  devise_scope :user do
    # TODO: verify if this is path is in use otherwise remove it.
    delete "profile/purge_avatar", to: "users/registrations#purge_avatar"
  end

  namespace :webhooks do
    post "stripe/checkout/fulfillment", to: "stripe#fulfill_stripe_checkout"
  end

  match "*path", via: :all, to: "home#index", constraints: lambda { |req|
    req.path.exclude? "rails/active_storage"
  }
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id              :bigint           not null, primary key
#  address         :text             not null
#  base_currency   :string           default("USD"), not null
#  business_phone  :string
#  country         :string           not null
#  date_format     :string
#  fiscal_year_end :string
#  name            :string           not null
#  standard_price  :decimal(, )      default(0.0), not null
#  timezone        :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

# frozen_string_literal: true

class Company < ApplicationRecord
  # Associations
  has_many :employments, dependent: :destroy
  has_many :users, through: :employments
  has_many :timesheet_entries, through: :users
  has_many :clients, dependent: :destroy
  has_many :projects, through: :clients, dependent: :destroy
  has_many :current_workspace_users, foreign_key: "current_workspace_id", class_name: "User", dependent: :nullify
  has_one_attached :logo
  has_many :timesheet_entries, through: :clients
  has_many :invoices, through: :clients
  has_many :payments, through: :invoices
  has_one :stripe_connected_account, dependent: :destroy
  has_many :payments_providers, dependent: :destroy
  has_many :addresses, as: :addressable, dependent: :destroy
  has_many :devices, dependent: :destroy
  has_many :invitations, dependent: :destroy
  resourcify

  # Validations
  validates :name, :business_phone, :standard_price, :country, :base_currency, presence: true
  validates :standard_price, numericality: { greater_than_or_equal_to: 0 }

  # scopes
  scope :valid_invitations, -> { where(company: self).valid_invitations }

  # Note: Possible dead fn
  def project_list(client_id = nil, user_id = nil, billable = nil, search)
    project_list = project_list_query(client_id, user_id, billable)
    minutes_spent = timesheet_entries.group(:project_id).sum(:duration)
    query = project_list.ransack({ name_or_client_name_cont: search })
    project_list = query.result
    project_ids = project_list.ids.uniq
    project_ids.map do |id|
      billable_array = []
      project_name_array = []
      client_name_array = []
      project_list.each do |project|
        if id == project.id
          billable_array.push(project.is_billable)
          client_name_array.push(project.project_client_name)
          project_name_array.push(project.project_name)
        end
      end
      {
        id:,
        name: project_name_array[0],
        clientName: client_name_array[0],
        isBillable: billable_array[0],
        minutesSpent: minutes_spent[id]
      }
    end
  end

  # Note: Possible dead fn
  def project_list_query(client_id, user_id, billable)
    db_query = projects.kept.left_outer_joins(:project_members).joins(:client)
    db_query = db_query.where(project_members: { user_id: }) if user_id.present?
    db_query = db_query.where(client_id:) if client_id.present?
    db_query = db_query.where(projects: { billable: }) if billable.present?
    db_query.select(
      "projects.id as id,
       projects.name as project_name,
       projects.billable as is_billable,
       clients.name as project_client_name")
  end

  # Note: Possible dead fn
  def client_details(time_frame = "week")
    clients.kept.map { |client| client.client_detail(time_frame) }
  end

  # Note: Possible dead fn
  def client_list
    clients.kept.map do |client|
      { id: client.id, name: client.name, email: client.email, phone: client.phone, address: client.address }
    end
  end

  def overdue_and_outstanding_and_draft_amount
    currency = base_currency
    status_and_amount = invoices.group(:status).sum(:amount)
    status_and_amount.default = 0
    outstanding_amount = status_and_amount["sent"] + status_and_amount["viewed"] + status_and_amount["overdue"]
    {
      overdue_amount: status_and_amount["overdue"],
      outstanding_amount:,
      draft_amount: status_and_amount["draft"],
      currency:
    }
  end

  # Note: Possible dead fn
  def user_details
    users.kept.map do |user|
      {
        id: user.id,
        name: user.full_name
      }
    end
  end

  def company_logo
    return nil if !logo.attached?

    Rails.application.routes.url_helpers.polymorphic_url(logo, only_path: true)
  end

  def stripe_account_id
    stripe_connected_account&.account_id
  end
end

app/controllers/companies/purge_logo_controller.rb
# frozen_string_literal: true

class Companies::PurgeLogoController < ApplicationController
  def destroy
    current_company.logo.destroy
    redirect_to company_path
  end
end

app/controllers/companies_controller.rb
# frozen_string_literal: true

class CompaniesController < ApplicationController
  skip_before_action :validate_company!, only: [:create, :new]

  def new
    @company = Company.new
    authorize @company
    render :new
  end

  def create
    @company = Company.new(permitted_attributes(Company))
    authorize @company
    if @company.save
      current_user.companies << @company
      current_user.current_workspace_id = @company.id
      current_user.add_role(:owner, @company)
      current_user.save!

      redirect_to root_path, notice: t(".success")
    else
      flash.now[:error] = t(".failure")
      render :new, status: :unprocessable_entity
    end
  end

  def show
    authorize current_company
  end

  def update
    authorize current_company
    if current_company.update(permitted_attributes(current_company))
      redirect_to company_path
      flash[:notice] = t(".success")
    else
      render :show, status: :unprocessable_entity
    end
  end
end

app/controllers/internal_api/v1/companies/purge_logo_controller.rb
# frozen_string_literal: true

class InternalApi::V1::Companies::PurgeLogoController < InternalApi::V1::ApplicationController
  def destroy
    authorize current_company, :purge_logo?
    current_company.logo.destroy
    render json: { notice: I18n.t("companies.purge_logo.destroy.success") }, status: :ok
  end
end

app/controllers/internal_api/v1/companies_controller.rb
# frozen_string_literal: true

class InternalApi::V1::CompaniesController < InternalApi::V1::ApplicationController
  def index
    authorize current_company
    render :index, locals: { current_company: }, status: :ok
  end

  def create
    authorize Company
    company = Company.new(company_params)
    if company.save!
      current_user.companies << company
      current_user.current_workspace_id = company.id
      current_user.add_role(:owner, company)
      current_user.save!
      render json: { notice: I18n.t("companies.create.success") }
    end
  end

  def update
    authorize current_company
    if current_company.update!(company_params)
      render json: { notice: I18n.t("companies.update.success") }
    end
  end

  private
    def company_params
      params.require(:company).permit(
        :name, :address, :business_phone, :country, :timezone, :base_currency,
        :standard_price, :fiscal_year_end, :date_format, :logo
      )
    end
end

app/views/companies/show.html.erb
<%= javascript_pack_tag "org_timezones", "data-turbo-track": "reload", defer: true %>
<div class="align-page__outer-wrapper">
  <div class="align-page__middle-wrapper">
    <div class="align-page__inner-wrapper">

      <%= form_with model: current_company, url: company_path(current_company), method: :put, local: true do |form| %>

        <div class="sm:flex sm:items-center sm:justify-between mt-6 mb-3">
          <div class="flex-1 min-w-0">
            <h2 class="text-3xl font-extrabold leading-7 text-gray-900 sm:text-4xl sm:truncate py-1">
              <%= t('settings.settings').capitalize %>
            </h2>
          </div>
          <div class="mt-6 flex sm:mt-0 md:ml-4">
            <%= link_to company_path, class:"form__cancel" do %>
              <%= image_tag("cancel_button.svg", class:"-ml-0.5 mr-2 h-4 w-4") %>
              <%= t('settings.cancel').upcase %>
            <% end %>
            <button type="submit" class="form__save">
              <%= image_tag("save_button.svg", class:"-ml-0.5 mr-2 h-4 w-4") %>
              <%= t('settings.save').upcase %>
            </button>
          </div>
        </div>
        <div class="sm:flex sm:items-center sm:justify-between mt-3 mb-3">
          <div class="flex-1 min-w-0">
            <h2 class="<%= request.path == "/profile" ? "underline font-extrabold" : "font-normal" %> text-xs text-miru-han-purple-1000 hover:text-miru-han-purple-600 tracking-widest leading-7 sm:text-base sm:truncate py-1 cursor-pointer">
              <%= link_to t('settings.profile_setting').upcase, "/profile" %>
            </h2>
          </div>
          <div class="flex-1 min-w-0">
            <h2 class="<%= request.path == "/company" ? "underline font-extrabold" : "font-normal" %> text-xs text-miru-han-purple-1000 hover:text-miru-han-purple-600 tracking-widest leading-7 sm:text-base sm:truncate py-1 cursor-pointer">
              <%= link_to t('settings.organization_setting').upcase, company_path %>
            </h2>
          </div>
          <div class="flex-1 min-w-0">
            <h2 class="<%= request.path == "/payments/settings" ? "underline font-extrabold" : "font-normal" %> text-xs text-miru-han-purple-1000 hover:text-miru-han-purple-600 tracking-widest leading-7 sm:text-base sm:truncate py-1 cursor-pointer">
              <%= link_to t('settings.payment_setting').upcase, payments_settings_path %>
            </h2>
          </div>
        </div>

        <div class="bg-miru-gray-100 p-10 mb-10">
          <div class="max-w-max sm:max-w-md">

            <div class="field">
              <label class="tracking-wider block text-sm font-semibold text-miru-dark-purple-1000"><%= t('company.logo').capitalize %></label>
              <div class="mt-1">
                <% if current_company.logo.attached? %>
                  <div class="flex items-center space-x-4 lg:space-x-6">
                    <div class="relative w-24 h-24 rounded-full border-solid border-4 border-miru-han-purple-1000 bg-white flex justify-center items-center hover:cursor-pointer">
                      <div class="flex items-center justify-center">
                        <%= image_tag current_company.logo, class: "rounded-full w-22 h-22" %>
                      </div>
                    </div>
                    <%= link_to image_tag("#{image_url 'delete_image_button.svg'}"), company_purge_logo_path, method: :delete, class: "font-medium text-lg leading-6 space-y-1 hover:border-2 hover:border-miru-han-purple-1000"%>
                  </div>
                <% else %>
                  <div x-data="showImage()">
                    <div class="relative w-24 h-24 rounded-md border-solid border-4 border-miru-han-purple-1000 bg-white flex justify-center items-center hover:cursor-pointer">
                      <div class="flex items-center justify-center">
                        <label>
                          <div class="flex flex-col items-center">
                            <img id="preview" class="absolute ml-1 mt-1 inset-0 w-20 h-20 rounded-md">
                            <img src="<%= image_url 'plus_icon.svg' %>" class="mt-8">
                            <div class="opacity-0" accept="image/*" @change="showPreview(event)">
                              <%= form.file_field :logo %>
                            </div>
                          </div>
                        </label>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>

            <div class="mt-4">
              <div class="field">
                <div class="field_with_errors">
                  <%= form.label t('company.company').capitalize, class: "tracking-wider block text-sm font-semibold text-miru-dark-purple-1000" %>
                  <div class="tracking-wider block text-xs text-red-600">
                    <%= error_message_on(form.object, :name) %>
                  </div>
                </div>
                <div class="mt-1">
                  <%= form.text_field :name, autofocus: true, autocomplete: "name", class: "rounded tracking-wider appearance-none border block w-full px-3 py-2 bg-miru-white-100 shadow-sm font-semibold text-xs text-miru-dark-purple-1000 focus:outline-none sm:text-base #{error_message_class(form.object, :name)}" %>
                </div>
              </div>
            </div>

            <div class="mt-4">
              <div class="field">
                <div class="field_with_errors">
                  <%= form.label t('company.address').capitalize, class: "tracking-wider block text-sm font-semibold text-miru-dark-purple-1000" %>
                  <div class="tracking-wider block text-xs text-red-600">
                    <%= error_message_on(form.object, :address) %>
                  </div>
                </div>
                <div class="mt-1">
                  <%= form.text_area :address, autofocus: true, autocomplete: "address", class: "rounded tracking-wider border block w-full px-3 py-2 bg-miru-white-100 shadow-sm font-semibold text-xs text-miru-dark-purple-1000 focus:outline-none sm:text-base #{error_message_class(form.object, :address)}" %>
                </div>
              </div>
            </div>

            <div class="mt-4">
              <div class="field">
                <div class="field_with_errors">
                  <%= form.label t('company.business_phone').capitalize, class: "tracking-wider block text-sm font-semibold text-miru-dark-purple-1000" %>
                  <div class="tracking-wider block text-xs text-red-600">
                    <%= error_message_on(form.object, :business_phone) %>
                  </div>
                </div>
                <div class="mt-1">
                  <%= form.text_field :business_phone, autofocus: true, autocomplete: "business-phone", class: "rounded tracking-wider appearance-none border block w-full px-3 py-2 bg-miru-white-100 shadow-sm font-semibold text-xs text-miru-dark-purple-1000 focus:outline-none sm:text-base #{error_message_class(form.object, :business_phone)}" %>
                </div>
              </div>
            </div>

            <div class="mt-4">
              <div class="field">
                <div class="field_with_errors">
                  <%= form.label t('company.country').capitalize, class: "tracking-wider block text-sm font-semibold text-miru-dark-purple-1000" %>
                  <div class="tracking-wider block text-xs text-red-600">
                    <%= error_message_on(form.object, :country) %>
                  </div>
                </div>
                <div class="mt-1">
                  <%= form.select :country, [[ "Please select", "", { selected: true, disabled: true }]] + ISO3166::Country.pluck(:alpha2, :iso_short_name).collect { |c| [ c.second, c.first ] }, {}, { autofocus: true, class: "select-country rounded tracking-wider border block w-full px-3 py-2 bg-miru-white-100 shadow-sm font-semibold text-xs text-miru-dark-purple-1000 focus:outline-none #{error_message_class(form.object, :country)}" } %>
                </div>
              </div>
            </div>

            <div class="mt-4">
              <div class="field">
                <div class="field_with_errors">
                  <%= form.label t('company.timezone').capitalize, class: "tracking-wider block text-sm font-semibold text-miru-dark-purple-1000" %>
                  <div class="tracking-wider block text-xs text-red-600">
                    <%= error_message_on(form.object, :timezone) %>
                  </div>
                </div>
                <div class="mt-1">
                  <%= form.select :timezone, ActiveSupport::TimeZone.country_zones(current_company.country), {}, { autofocus: true, class: "select-timezone rounded tracking-wider border block w-full px-3 py-2 bg-miru-white-100 shadow-sm font-semibold text-xs text-miru-dark-purple-1000 focus:outline-none #{error_message_class(form.object, :timezone)}" } %>
                </div>
              </div>
            </div>

            <div class="mt-4">
              <div class="field">
                <div class="field_with_errors">
                  <%= form.label t('company.base_currency').capitalize, class: "tracking-wider block text-sm font-semibold text-miru-dark-purple-1000" %>
                  <div class="tracking-wider block text-xs text-red-600">
                    <%= error_message_on(form.object, :base_currency) %>
                  </div>
                </div>

                <div class="mt-1">
                  <%= form.select :base_currency, Money::Currency.table.collect { |k, v| [ v[:name], v[:iso_code] ] }, {}, {autofocus: true, class: "rounded tracking-wider border block w-full px-3 py-2 bg-miru-white-100 shadow-sm font-semibold text-xs text-miru-dark-purple-1000 focus:outline-none #{error_message_class(form.object, :base_currency)}"} %>
                </div>
              </div>
            </div>

            <div class="mt-4">
              <div class="field">
                <div class="field_with_errors">
                  <%= form.label t('company.standard_price').capitalize, class: "tracking-wider block text-sm font-semibold text-miru-dark-purple-1000" %>
                  <div class="tracking-wider block text-xs text-red-600">
                    <%= error_message_on(form.object, :standard_price) %>
                  </div>
                </div>

                <div class="mt-1">
                  <%= form.number_field :standard_price, autofocus: true, autocomplete: "standard-price", class: "rounded tracking-wider border block w-full px-3 py-2 bg-miru-white-100 shadow-sm font-semibold text-xs text-miru-dark-purple-1000 focus:outline-none sm:text-base #{error_message_class(form.object, :standard_price)}" %>
                </div>
              </div>
            </div>

            <div class="mt-4">
              <div class="field">
                <div class="field_with_errors">
                  <%= form.label t('company.fiscal_year').capitalize, class: "tracking-wider block text-xs font-semibold text-miru-dark-purple-1000" %>
                  <div class="tracking-wider block text-xs text-red-600">
                    <%= error_message_on(form.object, :fiscal_year_end) %>
                  </div>
                </div>
                <div class="mt-1">
                  <%= form.select :fiscal_year_end, [[ "Please select", "", { selected: true, disabled: true }], ["January-December", "jan-dec",], ["April-March", "apr-mar"]], {}, {autofocus: true, class: "rounded tracking-wider border block w-full px-3 py-2 bg-miru-white-100 shadow-sm font-semibold text-xs text-miru-dark-purple-1000 focus:outline-none #{error_message_class(form.object, :fiscal_year_end)}"} %>
                </div>
              </div>
            </div>

            <div class="mt-4">
              <div class="field">
                <div class="field_with_errors">
                  <%= form.label t('company.date_format').capitalize, class: "tracking-wider block text-xs font-semibold text-miru-dark-purple-1000" %>
                  <div class="tracking-wider block text-xs text-red-600">
                    <%= error_message_on(form.object, :date_format) %>
                  </div>
                </div>
                <div class="mt-1">
                  <%= form.select :date_format, [[ "Please select", "", { selected: true, disabled: true }], ["DD-MM-YYYY"], ["MM-DD-YYYY"], ["YYYY-MM-DD"]], {}, {autofocus: true, class: "rounded tracking-wider border block w-full px-3 py-2 bg-miru-white-100 shadow-sm font-semibold text-xs text-miru-dark-purple-1000 focus:outline-none #{error_message_class(form.object, :date_format)}"} %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>