config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # For opening the email in the web browser in non production environments
  if ENV["EMAIL_DELIVERY_METHOD"] == "letter_opener_web"
    mount LetterOpenerWeb::Engine, at: "/sent_emails"
  end

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(username),
      ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
      ActiveSupport::SecurityUtils.secure_compare(
        ::Digest::SHA256.hexdigest(password),
        ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
  end
  mount Sidekiq::Web, at: "/sidekiq"

  root to: "root#index"
  draw(:internal_api)
  draw(:api)
  draw(:device_api)
  resources :dashboard, only: [:index]

  # get "*path", to: "home#index", via: :all
  resource :company, only: [:new, :show, :create, :update], controller: :companies do
    resource :purge_logo, only: [:destroy], controller: "companies/purge_logo"
  end

  resources :workspaces, only: [:update]

  resources :invoices, only: [], module: :invoices do
    resources :payments, only: [:new] do
      collection do
        get :success
        get :cancel
      end
    end

    member do
      get :view, to: "view#show", as: :view
    end
  end

  namespace :invitations do
    resources :accepts, only: [:index], controller: "accept"
  end

  get "users/invitation/accept", to: "invitations/accept#show"
  get "payments/settings/stripe/connect/refresh", to: "payment_settings#refresh_stripe_connect"
  get "payments/settings/*path", to: "payment_settings#index", via: :all
  get "payments/settings", to: "payment_settings#index"

  resource :email_confirmation, only: :show do
    get :resend
  end

  devise_scope :user do
    # TODO: verify if this is path is in use otherwise remove it.
    delete "profile/purge_avatar", to: "users/registrations#purge_avatar"
  end

  namespace :webhooks do
    post "stripe/checkout/fulfillment", to: "stripe#fulfill_stripe_checkout"
  end

  match "*path", via: :all, to: "home#index", constraints: lambda { |req|
    req.path.exclude? "rails/active_storage"
  }
end

app/controllers/internal_api/v1/team_controller.rb
# frozen_string_literal: true

class InternalApi::V1::TeamController < InternalApi::V1::ApplicationController
  helper ApplicationHelper

  def index
    authorize :index, policy_class: TeamPolicy
    # TODO: need to update either the search form or search logic in later PRs
    query = current_company.employments.kept.includes(user: [:roles, :avatar_attachment]).ransack(params[:q])
    invitations_query = current_company.invitations.valid_invitations
      .ransack(first_name_or_last_name_or_recipient_email_cont: params.dig(:q, :first_name_or_last_name_or_email_cont))
    teams = query.result(distinct: true)
    invitations = invitations_query.result(distinct: true)

    render :index, locals: { teams:, invitations: }, status: :ok
  end

  def update
    authorize employment, policy_class: TeamPolicy
    User.transaction do
      employment.user.skip_reconfirmation!
      employment.user.update!(user_params)
      update_company_user_role
    end
    render json: {
      user: employment.user,
      notice: I18n.t("team.update.success.message")
    }, status: :ok
  end

  def destroy
    authorize employment, policy_class: TeamPolicy
    employment.discard!
    render json: {
      user: employment.user,
      notice: I18n.t("team.delete.success.message")
    }, status: :ok
  end

  private
    def employment
      @_employment ||= current_company.employments.kept.find_by!(user_id: params[:id])
    end

    def user_params
      params.permit(policy(:team).permitted_attributes)
    end

    def update_company_user_role
      current_role = current_company_role(employment.user)

      employment.user.remove_role(current_role.name.to_sym, current_company) if current_role.present?
      employment.user.add_role(params[:role].downcase.to_sym, current_company)
    end

    def current_company_role(user)
      user.roles.find_by(resource: current_company)
    end
end

app/controllers/internal_api/v1/teams/transfer_wise_controller.rb
# frozen_string_literal: true

class InternalApi::V1::Teams::TransferWiseController < InternalApi::V1::ApplicationController
  skip_after_action :verify_authorized, only: :create

  def create
    recipient_service = Recipient::CreateService.new(
      user: current_user,
      recipient_account_params: params_for_create_recipient_account)
    render json: recipient_service.process, status: :created
  end

  private

    def params_for_create_recipient_account
      params.require(:recipient).permit(:currency, :profile, :type, :accountHolderName, :ownedByCustomer, details: {})
    end
end

app/helpers/team_helper.rb
# frozen_string_literal: true

module TeamHelper
  def resource_name
    :user
  end

  def resource
    @_resource ||= User.new
  end

  def devise_mapping
    @_devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/team/_display.html.erb
<td id="profilepicture-<%= member.id %>" class="px-6 py-4 whitespace-nowrap">
  <%= image_tag user_avatar(member), class: "h-10 w-10 rounded-full" %>
</td>
<td id="full_name-<%= member.id %>" class="px-6 py-4 whitespace-nowrap">
  <div class="flex items-center">
    <div class="text-base font-semibold text-miru-dark-purple-1000">
      <%= member.full_name.capitalize %>
    </div>
  </div>
</td>
<td id="email-<%= member.id %>" class="px-6 py-4 whitespace-nowrap text-sm font-medium text-miru-dark-purple-1000">
  <% if member.unconfirmed_email? %>
    Current Email : <%= member.email %><br/>
    Changed Email : <%= member.unconfirmed_email %>
  <% else %>
    <%= member.email %>
  <% end %>
</td>
<td id="role-<%= member.id %>" class="px-6 py-4 whitespace-nowrap text-sm font-medium text-miru-dark-purple-1000">
  <%= member.primary_role.titlecase %>
</td>
<td id="pending-<%= member.id %>" class="px-6 py-4 whitespace-nowrap">
  <% if current_user.has_any_role?(:owner, :admin) %>
    <% if member.unconfirmed_email? %>
      <span class="px-2 inline-flex text-xs leading-5 tracking-wider font-semibold rounded-full bg-miru-han-purple-100 text-miru-han-purple-1000">
        RECONFIRMATION PENDING
      </span>
    <% else %>
      <% unless member.invitation_accepted? %>
        <% if (member.id != current_user.id) %>
          <span class="px-2 inline-flex text-xs leading-5 tracking-wider font-semibold rounded-full bg-miru-han-purple-100 text-miru-han-purple-1000">
            INVITATION PENDING
          </span>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</td>
<td id="full_name-<%= member.id %>" class="px-4 py-4 whitespace-nowrap text-right text-sm font-medium">
  <% if current_user.has_any_role?(:owner, :admin) %>
    <%= link_to edit_team_path(member), remote: true do %>
      <img id="mid-<%= member.id %>" class="bottom h-7 w-7" src="<%= image_url 'edit_image_button.svg' %>" onclick="openModal('another-modal')">
    <% end %>
  <% end %>
</td>
<td class="px-4 py-4 whitespace-nowrap text-right text-sm font-medium">
  <% if current_user.has_any_role?(:owner, :admin) %>
    <%= link_to image_tag("#{image_url 'delete_image_button.svg'}"),team_path(member), method: :delete, class: "font-medium h-8 w-8 text-lg leading-6 space-y-1 hover:border-2 hover:border-miru-han-purple-1000"%>
  <% end %>
</td>

app/views/team/_form.html.erb
<%= form_with model: @user, url: team_path(@user), method: :put, remote: true do |f| %>
  <div class="mt-4">
    <div class="field">
      <label class="tracking-wider block text-xs font-normal text-miru-dark-purple-1000"><%= t('team.form_name') %></label>
      <div class="mt-2 flex -space-x-px">
        <div class="mr-4 w-1/2 flex-1 min-w-0">
          <%= f.text_field :first_name, class: "rounded tracking-wider appearance-none border border-gray-100 block w-full px-3 py-2 bg-miru-gray-100 h-8 shadow-sm font-medium text-sm text-miru-dark-purple-1000 focus:outline-none focus:ring-miru-gray-1000 focus:border-miru-gray-1000 sm:text-base" %>
        </div>
        <div class="w-1/2 flex-1 min-w-0">
          <%= f.text_field :last_name, class: "rounded tracking-wider appearance-none border border-gray-100 block w-full px-3 py-2 bg-miru-gray-100 h-8 shadow-sm font-medium text-sm text-miru-dark-purple-1000 focus:outline-none focus:ring-miru-gray-1000 focus:border-miru-gray-1000 sm:text-base" %>
        </div>
      </div>
    </div>
  </div>

  <div class="mt-4">
    <div class="field">
      <label class="tracking-wider block text-xs font-normal text-miru-dark-purple-1000">
        <%= t('team.form_email') %>
      </label>
      <div class="mt-2">
        <%= f.email_field :email, autocomplete: "email", class: "rounded tracking-wider bg-miru-gray-100 appearance-none border border-gray-100 block w-full px-3 py-2 h-8 shadow-sm font-medium text-sm text-miru-dark-purple-1000 focus:outline-none focus:ring-miru-gray-1000 focus:border-miru-gray-1000 sm:text-base" %>
      </div>
    </div>
  </div>
  <div class="mt-4">
    <div class="field">
      <label class="tracking-wider block text-xs font-normal text-miru-dark-purple-1000"><%= t('team.form_role') %></label>
      <div class="mt-1">
        <div class="space-y-4 sm:flex sm:items-center sm:space-y-0 sm:space-x-10">
          <div class="flex items-center">
            <%= f.radio_button :roles, "admin", :checked=>(@user.primary_role(current_company).titlecase == "Admin"), class: "focus:ring-miru-han-purple-1000 h-4 w-4 border-miru-han-purple-1000 text-miru-dark-purple-1000 cursor-pointer" %>
            <label for="admin" class="ml-3 block text-sm font-medium text-miru-dark-purple-1000">
              <%= t('team.form_admin') %>
            </label>
          </div>

          <div class="flex items-center">
            <%= f.radio_button :roles, "employee", :checked=>(@user.primary_role(current_company).titlecase == "Employee"), class: "focus:ring-miru-han-purple-1000 h-4 w-4 border-miru-han-purple-1000 text-miru-dark-purple-1000 cursor-pointer" %>
            <label for="Employee" class="ml-3 block text-sm font-medium text-miru-dark-purple-1000">
              <%= t('team.form_employee') %>
            </label>
          </div>

          <div class="flex items-center">
            <%= f.radio_button :roles, "book_keeper", :checked=>(@user.primary_role.titlecase == "Book Keeper"), class: "focus:ring-miru-han-purple-1000 h-4 w-4 border-miru-han-purple-1000 text-miru-dark-purple-1000 cursor-pointer" %>
            <label for="Book Keeper" class="ml-3 block text-sm font-medium text-miru-dark-purple-1000">
              <%= t('team.form_book_keeper') %>
            </label>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="mt-4">
    <div class="field">
      <label class="tracking-wider block text-xs font-normal text-miru-dark-purple-1000"><%= t('team.form_department') %></label>
      <div class="mt-2">
        <%= f.collection_select :department_id, User::DEPARTMENT_OPTIONS,:id,:name, { :prompt => 'Select a Department...' }, { class: "w-full p-1 border border-gray-300 rounded-md  focus:outline-none focus:ring focus:ring-indigo-100 focus:border-indigo-300" } %>
      </div>
    </div>
  </div>
  <div class="mt-4">
    <div class="field">
      <label class="tracking-wider block text-xs font-normal text-miru-dark-purple-1000"><%= t('team.form_team_lead') %></label>
      <div class="mt-1">
        <div class="space-y-4 sm:flex sm:items-center sm:space-y-0 sm:space-x-10">
          <div class="flex items-center">
            <%= f.radio_button :team_lead, true, :checked=>@user.team_lead, value: true, class: "focus:ring-miru-han-purple-1000 h-4 w-4 border-miru-han-purple-1000 text-miru-dark-purple-1000 cursor-pointer" %>
            <label for="Owner" class="ml-3 block text-sm font-medium text-miru-dark-purple-1000">
              Yes
            </label>
          </div>

          <div class="flex items-center">
            <%= f.radio_button :team_lead, false, :checked=>!@user.team_lead, value: false, class: "focus:ring-miru-han-purple-1000 h-4 w-4 border-miru-han-purple-1000 text-miru-dark-purple-1000 cursor-pointer" %>
            <label for="admin" class="ml-3 block text-sm font-medium text-miru-dark-purple-1000">
              No
            </label>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="mt-4">
    <div class="field">
      <div class="mt-2 flex -space-x-px">
        <label class="tracking-wider block text-xs font-normal text-miru-dark-purple-1000">
          <%= t('team.form_photo') %>
        </label>
        <% if @user.avatar.attached? %>
          <%= image_tag user_avatar(@user), class: "table__avatar", style: "margin-left: 10px;" %>
          <%= link_to 'Remove', url_for(controller: :team, action: :delete_avatar, id: @user.id, avatar_id: @user.avatar.id), method: :delete, data: { confirm: 'Are you sure?' }, style: "margin-left: 10px;color: #0033CC;" %>
        <% end %>
      </div>
      <div class="mt-2">
        <%= f.file_field :avatar, direct_upload: true, accept: "image/png,image/gif,image/jpeg", class: "rounded tracking-wider bg-miru-gray-100 appearance-none border border-gray-100 block w-full h-full px-3 py-2 h-8 shadow-sm font-medium text-sm text-miru-dark-purple-1000 focus:outline-none focus:ring-miru-gray-1000 focus:border-miru-gray-1000 sm:text-base" %>
      </div>
    </div>
  </div>
  <div class="actions mt-4">
    <%= f.submit "SAVE", class: "tracking-widest h-10 w-full flex justify-center py-1 px-4 border border-transparent shadow-sm text-base font-sans font-medium text-miru-white-1000 bg-miru-han-purple-1000 hover:bg-miru-han-purple-600 focus:outline-none rounded cursor-pointer"%>
  </div>
<% end %>

app/views/team/_invitation.html.erb
<td id="profilepicture-<%= invitation.id %>" class="table__data">
  <%= image_tag image_url("avatar.svg"), class: "table__avatar" %>
</td>
<td id="full_name-<%= invitation.id %>" class="table__data">
  <div class="flex items-center">
    <div class="table__name">
      <%= invitation.full_name.titleize %>
    </div>
  </div>
</td>
<td id="email-<%= invitation.id %>" class="table__data table__text">
    <%= invitation.recipient_email %>
</td>
<td id="role-<%= invitation.id %>" class="table__data table__text">
  <%= invitation.role.titlecase %>
</td>
<td id="pending-<%= invitation.id %>" class="table__data">
  <% if current_user.has_any_role?({ name: :owner, resource: current_company }, { name: :admin, resource: current_company }) %>
    <span class="table__pending">
      <%= t('team.invitation') %>
    </span>
  <% end %>
</td>
<td id="edit-<%= invitation.id %>" class="table__data table__button_design">
  <% if policy(invitation).edit? %>
    <%= link_to edit_invitation_path(invitation), remote: true do %>
      <div class="w-6">
        <img id="mid-<%= invitation.id %>" class="table__button" data-invitation-element="edit-invitation" data-cy="edit-invitation-button" src="<%= image_url 'edit_image_button.svg' %>">
      </div>
    <% end %>
  <% end %>
</td>
<td id="delete-<%= invitation.id %>" class="table__data table__button_design">
  <% if policy(invitation).destroy? %>
    <%= link_to invitation_path(invitation), data: { confirm: "Are you sure?" }, method: :delete do %>
      <div class="w-6">
        <%= image_tag 'delete_image_button.svg', class:"table__button", "data-cy": "delete-invitation-button" %>
      </div>
    <% end %>
  <% end %>
</td>

app/views/team/_new_team_member_form.html.erb
<%= form_for(resource, as: resource_name, url: invitation_path(resource_name), html: { method: :post }) do |f| %>
  <%= render "devise/shared/error_messages", resource: resource %>

  <div class="mt-4">
    <div class="field">
      <div class="field_with_errors">
        <label class="tracking-wider block text-xs font-normal text-miru-dark-purple-1000"><%= t('team.form_name') %></label>
        <%=
          if f.object.errors.include?(:first_name)
            error_message_on(f.object, :first_name)
          else
            error_message_on(f.object, :last_name)
          end
        %>
      </div>
      <div class="mt-1 flex -space-x-px">
        <div class="mr-4 w-1/2 flex-1 min-w-0">
          <%= f.text_field :first_name, id:"team_first_name",required: true, placeholder: t('team.first_name'),  class: "rounded tracking-wider appearance-none border block w-full px-3 py-2 bg-miru-gray-100 h-8 shadow-sm font-medium text-sm text-miru-dark-purple-1000 focus:outline-none sm:text-base #{error_message_class(f.object, :first_name)}" ,"data-cy": "new-member-firstName" %>
        </div>
        <div class="w-1/2 flex-1 min-w-0">
          <%= f.text_field :last_name, id:"team_last_name",required: true, placeholder: t('team.last_name'), class: "rounded tracking-wider appearance-none border block w-full px-3 py-2 bg-miru-gray-100 h-8 shadow-sm font-medium text-sm text-miru-dark-purple-1000 focus:outline-none sm:text-base #{error_message_class(f.object, :last_name)}" ,"data-cy": "new-member-lastname" %>
        </div>
      </div>
    </div>
  </div>
  <% resource.class.invite_key_fields.each do |field| -%>
    <div class="mt-4">
      <div class="field">
        <div class="field_with_errors">
          <label class="tracking-wider block text-xs font-normal text-miru-dark-purple-1000">
            <%= t('team.form_email') %>
          </label>
          <%= error_message_on(f.object, field) %>
        </div>
        <div class="mt-1">
          <%= f.text_field field, id:"team_email",required: true, placeholder: t('team.email'), class: "rounded tracking-wider appearance-none border block w-full px-3 py-2 bg-miru-gray-100 h-8 shadow-sm font-medium text-sm text-miru-dark-purple-1000 focus:outline-none sm:text-base #{error_message_class(f.object, field)}" , "data-cy": "new-member-email" %>
        </div>
      </div>
    </div>
  <% end -%>

  <div class="mt-4">
    <div class="field">
      <label class="tracking-wider block text-xs font-normal text-miru-dark-purple-1000"><%= t('team.form_role') %></label>
      <div class="mt-1">
        <div class="space-y-4 sm:flex sm:items-center sm:space-y-0 sm:space-x-10">
          <div class="flex items-center">
            <%= f.radio_button :roles, 'Admin', class: "focus:ring-miru-han-purple-1000 h-4 w-4 border-miru-han-purple-1000 text-miru-dark-purple-1000 cursor-pointer" , "data-cy": "admin-radio-button" %>
            <label for="admin" class="ml-3 block text-sm font-medium text-miru-dark-purple-1000">
              <%= t('team.form_admin') %>
            </label>
          </div>

          <div class="flex items-center">
            <%= f.radio_button :roles, 'Employee', :checked=>true , class: "focus:ring-miru-han-purple-1000 h-4 w-4 border-miru-han-purple-1000 text-miru-dark-purple-1000 cursor-pointer" , "data-cy": "employee-radio-button" %>
            <label for="Employee" class="ml-3 block text-sm font-medium text-miru-dark-purple-1000">
              <%= t('team.form_employee')%>
            </label>
          </div>

          <div class="flex items-center">
            <%= f.radio_button :roles, 'Book_keeper', class: "focus:ring-miru-han-purple-1000 h-4 w-4 border-miru-han-purple-1000 text-miru-dark-purple-1000 cursor-pointer" , "data-cy": "employee-radio-button" %>
            <label for="Book_keeper" class="ml-3 block text-sm font-medium text-miru-dark-purple-1000">
              <%= t('team.form_book_keeper')%>
            </label>
          </div>

        </div>
      </div>
    </div>
  </div>

  <%= f.hidden_field :current_workspace_id, value: current_company.id %>

  <div class="actions mt-4">
    <%= f.submit "SEND INVITE", class: "tracking-widest h-10 w-full flex justify-center py-1 px-4 border border-transparent shadow-sm text-base font-sans font-medium text-miru-white-1000 bg-miru-han-purple-1000 hover:bg-miru-han-purple-600 focus:outline-none rounded cursor-pointer" , "data-cy": "send-invite-button" %>
  </div>

<% end %>

app/views/team/_team.html.erb
<td id="profilepicture-<%= member.id %>" class="table__data">
  <%= image_tag user_avatar(member), class: "table__avatar" %>
</td>
<td id="full_name-<%= member.id %>" class="table__data <%= member.discarded_at ? 'table__text_discarded' : 'table__text'%>">
  <%= member.full_name.titleize %>
</td>
<td id="email-<%= member.id %>" class="table__data <%= member.discarded_at ? 'table__text_discarded' : 'table__text'%>">
  <% if member.unconfirmed_email? %>
    <%= t('team.current_email') %> : <%= member.email %><br/>
    <%= t('team.changed_email') %>: <%= member.unconfirmed_email %>
  <% else %>
    <%= member.email %>
  <% end %>
</td>
<td id="role-<%= member.id %>" class="table__data <%= member.discarded_at ? 'table__text_discarded' : 'table__text'%>">
  <%= member.primary_role(current_company).titlecase %>
</td>
<td id="department-<%= member.id %>" class="table__data <%= member.discarded_at ? 'table__text_discarded' : 'table__text'%>">
  <%= member.department_name %>
</td>
<td id="team_lead-<%= member.id %>" class="table__data table__text text-center">
  <% if member.team_lead %>
    <span style="font-size:150%; font-weight:bold; color:green;">&#10004;</span>
  <% end %>
</td>
<td id="pending-<%= member.id %>" class="table__data">
  <% if current_user.has_any_role?({ name: :owner, resource: current_company }, { name: :admin, resource: current_company }) %>
    <% if member.unconfirmed_email?  %>
      <span class="table__pending">
        <%= t('team.reconfirmation') %>
      </span>
    <% end %>
  <% end %>
</td>
<td id="edit-<%= member.id %>" class="table__data table__button_design">
  <% if policy(:team).edit? %>
    <%= link_to edit_team_path(member), remote: true do %>
      <div class="w-6">
        <img id="mid-<%= member.id %>" class="table__button" data-team-element="edit-member" data-cy="edit-team-member-button" src="<%= image_url 'edit_image_button.svg' %>">
      </div>
    <% end %>
  <% end %>
</td>
<td id="delete-<%= member.id %>" class="table__data table__button_design">
  <% if policy(:team).destroy? %>
    <%= link_to team_path(member), data: { confirm: "Are you sure?" }, method: :delete do %>
      <div class="w-6">
        <%= image_tag 'delete_image_button.svg', class:"table__button", "data-cy": "delete-team-member-button" %>
      </div>
    <% end %>
  <% end %>
</td>

app/views/team/edit.js.erb
$("#team-modal").html("<%= j(render 'form') %>");

app/views/team/index.html.erb
<div class="max-w-6xl mx-auto px-2 md:px-11 font-manrope">
  <div>
    <%= react_component("Team/RouteConfig", {
      isAdminUser: current_user.has_role?(:book_keeper, current_user.current_workspace) || current_user.has_role?(:admin, current_user.current_workspace) || current_user.has_role?(:owner, current_user.current_workspace)
    }) %>
  </div>
 </div>

app/views/team/new.js.erb
var modal = $("#invitation-modal").parent();
var modal_header = modal.find(".modal__title");

modal_header.text("<%= I18n.t("team.create_new_user") %>");
$("#invitation-modal").html("<%= j(render partial: "invitations/form", locals: { invitation: @invitation }) %>");